// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
  show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtmU1gEU9yhnjYWezOqBZWj6yYTmGB4Xw',
    appId: '1:876939961946:web:7e3e67a75e39749b835a63',
    messagingSenderId: '876939961946',
    projectId: 'login-8a5a2',
    authDomain: 'login-8a5a2.firebaseapp.com',
    storageBucket: 'login-8a5a2.firebasestorage.app',
    measurementId: 'G-3HH1WG4ZN3',
  );
  
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9M8PrupeqsOuf6c2udjwi8cayRxN___U',
    appId: '1:876939961946:android:a051deeb7234a1c8835a63',
    messagingSenderId: '876939961946',
    projectId: 'login-8a5a2',
    storageBucket: 'login-8a5a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD40Z7OySvXlzlRns-UdonbJk1U_L5fJy4',
    appId: '1:876939961946:ios:61cd97ccba9650d5835a63',
    messagingSenderId: '876939961946',
    projectId: 'login-8a5a2',
    storageBucket: 'login-8a5a2.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD40Z7OySvXlzlRns-UdonbJk1U_L5fJy4',
    appId: '1:876939961946:ios:61cd97ccba9650d5835a63',
    messagingSenderId: '876939961946',
    projectId: 'login-8a5a2',
    storageBucket: 'login-8a5a2.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtmU1gEU9yhnjYWezOqBZWj6yYTmGB4Xw',
    appId: '1:876939961946:web:d48f5d5df8a9aec7835a63',
    messagingSenderId: '876939961946',
    projectId: 'login-8a5a2',
    authDomain: 'login-8a5a2.firebaseapp.com',
    storageBucket: 'login-8a5a2.firebasestorage.app',
    measurementId: 'G-Y1LJ174K9S',
  );
}
